### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by mreineck** [information-field-theory/nifty#26]
This Github repository has been superseded by the Gitlab one at https://gitlab.mpcdf.mpg.de/ift/NIFTy/.
Can we mention this here in some way?

**Comment by ensslin** [comment]
On 27.04.2018 18:36, Marco Selig wrote:
> i suggest you alter the README ... starting with a headline and the link ... given my limited access ... this sounds like a job for @ensslin @ultimanet (both are owners)
> 


done.
TOrsten

**Comment by mreineck** [comment]
Thanks!
